- name: Setup hosting server
  hosts: default

  vars:
      ansible_python_interpreter: '/usr/bin/python3'
      caddy_file: '/home/ubuntu/Caddyfile'
      caddy_sites_directory: '/home/ubuntu/sites-enabled'
      docker_install_compose: false
      docker_users:
          - ubuntu
      pip_install_packages:
          - name: docker
      security_autoupdate_reboot: true
      security_sudoers_passwordless: ['ubuntu']
      swap_file_size_mb: 8192
      vault_directory: '/home/ubuntu/vault'

  pre_tasks:
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        upgrade: dist

  roles:
      - role: geerlingguy.docker
      - role: geerlingguy.pip
      - role: geerlingguy.security
      - role: geerlingguy.swap

  tasks:
    - name: Setup developer keys
      authorized_key:
          user: ubuntu
          state: present
          key: "{{ lookup('file','support/id_ed25519.pub') }}"
          exclusive: yes

    - import_tasks: tasks/websites.yml
